[dependency.sh]
optional = false
scope = "Node" # Node | Cluster | Project | Client
collection = "Executor"

[dependency.python]
optional = false
scope = "Client" # Node | Cluster | Project | Client
collection = "Executor"
